repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name 'CurseMaven'
        url 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }

}