# Gradle Properties
org.gradle.jvmargs   = -Xmx4G
org.gradle.parallel  = true

# Mod Information
mod_version          = 1.0.1
mod_version_type     = release
mod_package          = team.terrafirmagreg
mod_id               = mod
mod_name             = Mod
mod_name_suffix      = Template

# Mod Metadata
mod_description      = Mod template.
mod_url              = https://github.com/TerraFirmaGreg-Team/Mod-Template
mod_authors          = TerraFirmaGreg
mod_credits          = TerraFirmaGreg-Team and before.
mod_logo_path        = /logo.png

# Mapping & Runtime
minecraft_version    = 1.20.1

# Loader
loader               = forge
loader_version_range = [47,)
loader_version       = 47.4.13

# Build environment
java_version         = 17
gradle_version       = 8.12.1
mdg_legacy_version   = 2.0.119
spotless_version     = 7.2.1